<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ADDStock')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
</head>
<body>
<!-- header -->
<div id="top-nav" class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('admin') ?>">
                <img src="<?= $this->basePath('img/your-logo-here.png') ?>" height="30" alt="ADDStock"/>&nbsp;
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#"><i
                                class="glyphicon glyphicon-user"></i> Admin <span class="caret"></span></a>
                    <ul id="g-account-menu" class="dropdown-menu" role="menu">
                        <li><a href="#">My Profile</a></li>
                    </ul>
                </li>
                <li><a href="#"><i class="glyphicon glyphicon-lock"></i> Logout</a></li>
            </ul>
        </div>
    </div>
    <!-- /container -->
</div>
<!-- /Header -->

<!-- Main -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3">
            <!-- Left column -->
            <a href="#"><strong><i class="glyphicon glyphicon-wrench"></i> Tools</strong></a>

            <hr>

            <?php
            $this->verticalMenu()->setItems(
                [
                    [
                        'id' => 'setting',
                        'label' => 'Setting',
                        'icon' => 'glyphicon-chevron-down',
                        'target' => 'userMenu',
                        'expanded' => 'in',
                        'dropdown' => [
                            [
                                'id' => 'home',
                                'label' => 'Home',
                                'icon' => 'glyphicon-home',
                                'link' => '#'
                            ],
                            [
                                'id' => 'messages',
                                'label' => 'Messages',
                                'icon' => 'glyphicon-envelope',
                                'extra' => '<span class="badge badge-info">4</span>',
                                'link' => '#'
                            ],
                            [
                                'id' => 'options',
                                'label' => 'Options',
                                'icon' => 'glyphicon-cog',
                                'link' => '#'
                            ],
                            [
                                'id' => 'shoutbox',
                                'label' => 'Shoutbox',
                                'icon' => 'glyphicon-comment',
                                'link' => '#'
                            ],
                            [
                                'id' => 'staff-list',
                                'label' => 'Staff List',
                                'icon' => 'glyphicon-user',
                                'link' => '#'
                            ],
                            [
                                'id' => 'transactions',
                                'label' => 'Transactions',
                                'icon' => 'glyphicon-flag',
                                'link' => '#'
                            ],
                            [
                                'id' => 'rules',
                                'label' => 'Rules',
                                'icon' => 'glyphicon-exclamation-sign',
                                'link' => '#'
                            ],
                            [
                                'id' => 'logout',
                                'label' => 'Logout',
                                'icon' => 'glyphicon-off',
                                'link' => '#'
                            ],
                        ],
                    ],
                    [
                        'id' => 'reports',
                        'label' => 'Reports',
                        'icon' => 'glyphicon-chevron-right',
                        'target' => 'menu2',
                        'dropdown' => [
                            [
                                'id' => 'information-tats',
                                'label' => 'Information &amp; Stats',
                                'link' => '#'
                            ],
                            [
                                'id' => 'views',
                                'label' => 'Views',
                                'link' => '#'
                            ],
                            [
                                'id' => 'requests',
                                'label' => 'Requests',
                                'link' => '#'
                            ],
                            [
                                'id' => 'Timetable',
                                'label' => 'timetable',
                                'link' => '#'
                            ],
                            [
                                'id' => 'alerts',
                                'label' => 'Alerts',
                                'link' => '#'
                            ],
                        ],
                    ],
                    [
                        'id' => 'social-media',
                        'label' => 'Social Media',
                        'icon' => 'glyphicon-chevron-right',
                        'target' => 'menu3',
                        'dropdown' => [
                            [
                                'id' => 'facebook',
                                'label' => 'Facebook',
                                'icon' => 'glyphicon-circle',
                                'link' => '#'
                            ],
                            [
                                'id' => 'twitter',
                                'label' => 'Twitter',
                                'icon' => 'glyphicon-circle',
                                'link' => '#'
                            ],
                        ]
                    ],
                ]
            );

            echo $this->verticalMenu()->render();
            ?>

            <hr>

            <a href="#"><strong><i class="glyphicon glyphicon-link"></i> Resources</strong></a>

            <hr>

            <ul class="nav nav-pills nav-stacked">
                <li class="nav-header"></li>
                <li><a href="#"><i class="glyphicon glyphicon-list"></i> Layouts &amp; Templates</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-briefcase"></i> Toolbox</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-link"></i> Widgets</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-list-alt"></i> Reports</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-book"></i> Pages</a></li>
                <li><a href="#"><i class="glyphicon glyphicon-star"></i> Social Media</a></li>
            </ul>

            <hr>
            <ul class="nav nav-stacked">
                <li class="active"><a href="http://bootply.com" title="The Bootstrap Playground" target="ext">Playground</a></li>
                <li><a href="/tagged/bootstrap-3">Bootstrap 3</a></li>
                <li><a href="/61518" title="Bootstrap 3 Panel">Panels</a></li>
                <li><a href="/61521" title="Bootstrap 3 Icons">Glyphicons</a></li>
                <li><a href="/62603">Layout</a></li>
            </ul>

            <hr>

            <a href="#"><strong><i class="glyphicon glyphicon-list"></i> More Templates</strong></a>

            <hr>

            <ul class="nav nav-stacked">
                <li class="active"><a rel="nofollow" href="http://goo.gl/pQoXEh" target="ext">Premium Themes</a></li>
                <li><a rel="nofollow" href="https://wrapbootstrap.com/?ref=bootply">Wrap Bootstrap</a></li>
                <li><a rel="nofollow" href="http://bootstrapzero.com">BootstrapZero</a></li>
            </ul>
        </div>
        <!-- /col-3 -->
        <div class="col-sm-9">

            <!-- column 2 -->
            <ul class="list-inline pull-right">
                <li><a href="#"><i class="glyphicon glyphicon-cog"></i></a></li>
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-comment"></i><span class="count">3</span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">1. Is there a way..</a></li>
                        <li><a href="#">2. Hello, admin. I would..</a></li>
                        <li><a href="#"><strong>All messages</strong></a></li>
                    </ul>
                </li>
                <li><a href="#"><i class="glyphicon glyphicon-user"></i></a></li>
                <li><a title="Add Widget" data-toggle="modal" href="#addWidgetModal"><span class="glyphicon glyphicon-plus-sign"></span> Add Widget</a></li>
            </ul>
            <a href="#"><strong><i class="glyphicon glyphicon-dashboard"></i> My Dashboard</strong></a>
            <hr>
            <?= $this->content ?>
            <hr>

            <a href="#"><strong><i class="glyphicon glyphicon-comment"></i> Discussions</strong></a>

            <hr>

            <div class="row">
                <div class="col-md-12">
                    <ul class="list-group">
                        <li class="list-group-item"><a href="#"><i class="glyphicon glyphicon-flash"></i> <small>(3 mins ago)</small> The 3rd page reports don't contain any links. Does anyone know why..</a></li>
                        <li class="list-group-item"><a href="#"><i class="glyphicon glyphicon-flash"></i> <small>(1 hour ago)</small> Hi all, I've just post a report that show the relationship betwe..</a></li>
                        <li class="list-group-item"><a href="#"><i class="glyphicon glyphicon-heart"></i> <small>(2 hrs ago)</small> Paul. That document you posted yesterday doesn't seem to contain the over..</a></li>
                        <li class="list-group-item"><a href="#"><i class="glyphicon glyphicon-heart-empty"></i> <small>(4 hrs ago)</small> The map service on c243 is down today. I will be fixing the..</a></li>
                        <li class="list-group-item"><a href="#"><i class="glyphicon glyphicon-heart"></i> <small>(yesterday)</small> I posted a new document that shows how to install the services layer..</a></li>
                        <li class="list-group-item"><a href="#"><i class="glyphicon glyphicon-flash"></i> <small>(yesterday)</small> ..</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!--/col-span-9-->
    </div>
</div>
<!-- /Main -->

<footer class="text-center">This Bootstrap 3 dashboard layout is compliments of <a href="http://www.bootply.com/85850"><strong>Bootply.com</strong></a></footer>

<div class="modal" id="addWidgetModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Add Widget</h4>
            </div>
            <div class="modal-body">
                <p>Add a widget stuff here..</p>
            </div>
            <div class="modal-footer">
                <a href="#" data-dismiss="modal" class="btn">Close</a>
                <a href="#" class="btn btn-primary">Save changes</a>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dalog -->
</div>
<!-- /.modal -->
<!-- script references -->
<script src="/js/jquery-3.1.0.min.js"></script>
<script src="/js/bootstrap.js/bootstrap.min.js"></script>
<script src="/js/scripts.js"></script>

<?= $this->inlineScript() ?>
</body>
</html>
